/**
 * Contract rev 2 (Claude 3946b53, PROPOSED; merged into integ/scenario-candidate at f472aef):
 * the gallery against Claude's own published fixture pack, copied unmodified to
 * fixtures/rev2/. SIMULATED data: nothing here came from Scenario.
 */
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it, vi } from "vitest";
import { allAttributeValues, byAttr, byClass, byTag, flush } from "./fakeDom.js";
import { setup, card, cards, button, panel } from "./helpers.js";
import { BILLING_OUTCOME, JOB_STATUS, SUBMISSION_UNKNOWN_WARNING } from "../../src/lib/projects/conceptGallery/contract.js";
import {
  ASSET_MESSAGES, BILLING_TEXT, ERROR_KIND, FAILED_MESSAGES, LIST_MESSAGES, PRIOR_SUBMISSION_UNKNOWN_MESSAGE, classifyError,
} from "../../src/lib/projects/conceptGallery/errors.js";
import { normalizeJob } from "../../src/lib/projects/conceptGallery/state.js";
import { billingText } from "../../src/lib/projects/conceptGallery/render.js";
import * as publicApi from "../../src/lib/projects/conceptGallery/index.js";
import { JOB_VIEW_KEYS, USAGE_KEYS, STORAGE_KEYS, ASSET_VIEW_KEYS, OUTPUT_KEYS, CONCEPT_KEYS } from "./fixtures/contractFixtures.js";

const DIR = join(dirname(fileURLToPath(import.meta.url)), "fixtures", "rev2");
const fx = (name) => JSON.parse(readFileSync(join(DIR, name), "utf8"));
const body = (name) => fx(name).response;
/** A fixture error file as the rejection a CreativeJobsClient would throw. */
function fixtureError(name) {
  const f = fx(name);
  const e = new Error(f.response.error);
  return Object.assign(e, { status: f._fixture.httpStatus, code: f.response.code, details: f.response.details });
}
const LIST = body("jobs.list.200.json").jobs;
const byStatus = (s, code) => LIST.find((j) => j.status === s && (!code || j.error?.code === code));

/** Never claim a provider request cost nothing (contract rev 2 R2-4, §4). */
const FREE_CLAIM = /no charge|not charged|free of charge|\bfree\b|nothing (was|is|will be) charged|wasn't charged|won't be charged|without charge|didn't cost|cost nothing/i;

function setupList(jobs, extra = {}, handlers = {}) {
  const downloads = [];
  const ctx = setup(
    { listJobs: () => ({ ok: true, jobs }), getJob: () => new Promise(() => {}), getAssetUrl: () => body("asset.200.json"), ...handlers },
    { startDownload: (d) => downloads.push(d), onOpenConcept: () => {}, ...extra },
  );
  return { ...ctx, downloads };
}

describe("rev 2 fixture pack: provenance and shape", () => {
  it("every JSON file is marked simulated, not generated by Scenario", () => {
    const files = readdirSync(DIR).filter((f) => f.endsWith(".json"));
    expect(files.length).toBe(32);
    for (const f of files) expect(fx(f)._fixture, f).toMatchObject({ simulated: true, generatedByScenario: false });
  });

  it("job views match the shared fixture key sets (usage includes billingOutcome)", () => {
    const views = [...LIST, ...["job.failed.200.json", "job.processing.200.json", "job.succeeded.200.json", "job.submission-unknown.200.json"].map((f) => body(f).job)];
    for (const j of views) {
      expect(Object.keys(j).sort()).toEqual([...JOB_VIEW_KEYS].sort());
      expect(Object.keys(j.usage).sort()).toEqual([...USAGE_KEYS].sort());
      expect(Object.values(BILLING_OUTCOME)).toContain(j.usage.billingOutcome);
      expect(Object.keys(j.storage).sort()).toEqual([...STORAGE_KEYS].sort());
      expect(Object.keys(j.concept).sort()).toEqual([...CONCEPT_KEYS].sort());
      for (const o of j.outputs) expect(Object.keys(o).sort()).toEqual([...OUTPUT_KEYS].sort());
    }
    expect(Object.keys(body("asset.200.json").asset).sort()).toEqual([...ASSET_VIEW_KEYS].sort());
  });

  it("the list has no title, thumbnail or paging field (the contract request in CONCEPT_GALLERY.md)", () => {
    const listBody = body("jobs.list.200.json");
    expect(Object.keys(listBody).sort()).toEqual(["jobs", "ok"]);
    for (const j of LIST) expect(Object.keys(j)).not.toEqual(expect.arrayContaining(["title"]));
    expect(JSON.stringify(listBody)).not.toMatch(/thumbnail|preview|nextCursor|title/i);
  });

  it("synthetic GLB and PNG are what they say", () => {
    const glb = readFileSync(join(DIR, "SYNTHETIC-box-not-scenario-generated.glb"));
    expect(glb.subarray(0, 4).toString("latin1")).toBe("glTF");
    expect(glb.readUInt32LE(8)).toBe(glb.length);
    const png = readFileSync(join(DIR, "SYNTHETIC-reference-drawing.png"));
    expect([...png.subarray(1, 4)].map((c) => String.fromCharCode(c)).join("")).toBe("PNG");
  });
});

describe("rev 2: billingOutcome", () => {
  it("normalizeJob keeps outcome / reported cost / unit, never estimatedCost", () => {
    const ok = normalizeJob(byStatus("succeeded"));
    expect(ok.billing).toEqual({ outcome: "reported", reportedCost: 12, unit: "provider_cost_units" });
    expect(JSON.stringify(ok)).not.toMatch(/estimatedCost/);
    expect(normalizeJob(byStatus("processing")).billing).toEqual({ outcome: "unconfirmed", reportedCost: null, unit: null });
    expect(normalizeJob({ jobId: "x", usage: { billingOutcome: "free", reportedCost: 0 } }).billing.outcome).toBeNull();
    expect(normalizeJob({ jobId: "x", usage: { billingOutcome: "unconfirmed", reportedCost: 5 } }).billing.reportedCost).toBeNull();
    expect(normalizeJob({ jobId: "x" }).billing.outcome).toBeNull();
  });

  it("each outcome renders its own truthful line, and data-billing carries the value", async () => {
    const notSubmitted = { ...byStatus("processing"), jobId: "sub-1", status: "submitting", submittedAt: null, usage: { estimatedCost: 12, reportedCost: null, unit: "provider_cost_units", billingOutcome: "not_submitted" } };
    const rev1 = { ...byStatus("succeeded"), jobId: "rev1-1", usage: { estimatedCost: 12, reportedCost: 12, unit: "provider_cost_units" } };
    const jobs = [...LIST, notSubmitted, rev1];
    const { root } = setupList(jobs);
    await flush();
    const line = (id) => byAttr(card(root, id), "data-billing")[0];
    expect(line(byStatus("succeeded").jobId).getAttribute("data-billing")).toBe("reported");
    expect(line(byStatus("succeeded").jobId).textContent).toBe("Cost reported by the generation service: 12 provider units (unit unverified).");
    expect(line(byStatus("processing").jobId).textContent).toBe(BILLING_TEXT.unconfirmedPending);
    expect(line(byStatus("submission_unknown").jobId).textContent).toBe(BILLING_TEXT.unconfirmed);
    expect(line(byStatus("submission_unknown").jobId).textContent).toMatch(/may have been charged/i);
    for (const j of LIST.filter((x) => x.status === "failed")) {
      expect(line(j.jobId).getAttribute("data-billing")).toBe("unconfirmed");
      expect(line(j.jobId).textContent).toMatch(/may have been charged/i);
    }
    expect(line("sub-1").getAttribute("data-billing")).toBe("not_submitted");
    expect(line("sub-1").textContent).toBe(BILLING_TEXT.not_submitted);
    expect(line("rev1-1").getAttribute("data-billing")).toBe("unknown");
    expect(line("rev1-1").textContent).toBe("Not reported by this server.");
    expect(root.textContent).not.toMatch(FREE_CLAIM);
    expect(root.textContent).not.toMatch(/estimated/i);
  });

  it("no exported string, in any message table, claims a request was free", () => {
    const strings = [
      ...Object.values(LIST_MESSAGES), ...Object.values(ASSET_MESSAGES), ...Object.values(FAILED_MESSAGES),
      ...Object.values(BILLING_TEXT).map((v) => (typeof v === "function" ? v(0, "provider_cost_units") : v)),
      PRIOR_SUBMISSION_UNKNOWN_MESSAGE, SUBMISSION_UNKNOWN_WARNING,
    ];
    for (const s of strings) expect(s).not.toMatch(FREE_CLAIM);
  });

  it("a reported cost of 0 is shown as the number the service reported, not as 'free'", () => {
    const j = normalizeJob({ jobId: "z", status: "succeeded", usage: { billingOutcome: "reported", reportedCost: 0, unit: "provider_cost_units" } });
    expect(billingText(j)).toBe("Cost reported by the generation service: 0 provider units (unit unverified).");
  });

  it("PRIOR_SUBMISSION_UNKNOWN wording (for a host's Generate flow) says it may have been charged", () => {
    expect(publicApi.PRIOR_SUBMISSION_UNKNOWN_MESSAGE).toBe(PRIOR_SUBMISSION_UNKNOWN_MESSAGE);
    expect(PRIOR_SUBMISSION_UNKNOWN_MESSAGE).toMatch(/may have been charged/);
    expect(fx("error.prior-submission-unknown.409.json").response.code).toBe("PRIOR_SUBMISSION_UNKNOWN");
  });
});

describe("rev 2: the published list renders truthfully", () => {
  it("seven cards, server order, statuses and actions only where available", async () => {
    const { root } = setupList(LIST);
    await flush();
    expect(cards(root).map((c) => c.getAttribute("data-job-id"))).toEqual(LIST.map((j) => j.jobId));
    expect(cards(root).map((c) => c.getAttribute("data-status"))).toEqual(LIST.map((j) => j.status));
    const ok = card(root, byStatus("succeeded").jobId);
    expect(byAttr(ok, "data-action").map((b) => b.getAttribute("data-action"))).toEqual(["open", "download"]);
    for (const j of LIST.filter((x) => x.status !== "succeeded")) expect(byTag(card(root, j.jobId), "button"), j.status).toHaveLength(0);
    expect(byTag(root, "img")).toHaveLength(0);
    expect(byAttr(root, "data-thumbnail", "none")).toHaveLength(LIST.length);
  });

  it("title is '3D concept · <created date>', job id kept as a meta row", async () => {
    const { root } = setupList(LIST);
    await flush();
    const j = LIST[0];
    expect(byClass(card(root, j.jobId), "fcg-card-title")[0].textContent).toBe(`3D concept · D(${j.createdAt})`);
    expect(byClass(card(root, j.jobId), "fcg-id")[0].textContent).toBe(j.jobId);
  });

  it("failed jobs: own sentence per known code, the provider's reason for PROVIDER_GENERATION_FAILED", async () => {
    const { root } = setupList(LIST);
    await flush();
    const text = (code) => byAttr(card(root, byStatus("failed", code).jobId), "data-failed", code)[0].textContent;
    expect(text("PROVIDER_REJECTED_REQUEST")).toBe(`Generation failed. ${FAILED_MESSAGES.PROVIDER_REJECTED_REQUEST}`);
    expect(text("PROVIDER_RATE_LIMITED")).toBe(`Generation failed. ${FAILED_MESSAGES.PROVIDER_RATE_LIMITED}`);
    expect(text("PROVIDER_INSUFFICIENT_CREDITS")).toBe(`Generation failed. ${FAILED_MESSAGES.PROVIDER_INSUFFICIENT_CREDITS}`);
    expect(text("PROVIDER_GENERATION_FAILED")).toBe("Generation failed. simulated generation failure");
    expect(root.textContent).not.toMatch(/rate-limiting requests|Whether the provider charged/); // server prose not shown
  });

  it("submission_unknown keeps the exact warning, no buttons, not polled", async () => {
    const su = byStatus("submission_unknown");
    const { root, gallery } = setupList([su]);
    await flush();
    expect(byAttr(card(root, su.jobId), "data-submission-unknown")[0].textContent).toBe(`May have been charged. ${SUBMISSION_UNKNOWN_WARNING}`);
    expect(byAttr(root, "data-action").map((n) => n.getAttribute("data-action"))).toEqual(["refresh"]);
    expect(root.textContent).not.toMatch(/Try again|Retry|Resubmit|Generate/);
    expect(gallery.getState().polling).toBe(false);
  });

  it("succeeded: file storage says there is no FurniAI copy; Download resolves fresh from the asset fixture", async () => {
    const ok = byStatus("succeeded");
    const { root, client, downloads } = setupList([ok]);
    await flush();
    expect(byAttr(card(root, ok.jobId), "data-durable-copy", "false")[0].textContent).toMatch(/FurniAI keeps no copy/);
    button(root, "download").click();
    await flush();
    button(root, "download").click();
    await flush();
    expect(client.count("getAssetUrl")).toBe(2);
    expect(downloads).toHaveLength(2);
    expect(downloads[0].url).toBe("https://fixtures.invalid/SYNTHETIC-box-not-scenario-generated.glb");
    expect(root.textContent + allAttributeValues(root).join(" ")).not.toMatch(/fixtures\.invalid/); // the address never reaches the DOM
  });

  it("the processing job is polled; the terminal ones are not", async () => {
    const { gallery } = setupList(LIST);
    await flush();
    expect(gallery.getState().polling).toBe(true);
    expect(gallery.getState().jobs.filter((j) => j.status === JOB_STATUS.PROCESSING)).toHaveLength(1);
  });
});

describe("rev 2: GET error fixtures", () => {
  const cases = [
    ["error.missing-auth.401.json", ERROR_KIND.SIGNED_OUT],
    ["error.missing-job.404.json", ERROR_KIND.NOT_FOUND],
    ["error.asset-not-ready.409.json", ERROR_KIND.ASSET_NOT_READY],
    ["error.asset-unavailable.410.json", ERROR_KIND.ASSET_UNAVAILABLE],
    ["error.not-configured.503.json", ERROR_KIND.NOT_CONFIGURED],
    ["error.generation-disabled.503.json", ERROR_KIND.NOT_CONFIGURED],
    ["error.provider-rate-limited.429.json", ERROR_KIND.RATE_LIMITED],
    ["error.provider-insufficient-credits.402.json", ERROR_KIND.PROVIDER_REFUSED],
    ["error.provider-auth-rejected.502.json", ERROR_KIND.PROVIDER_REFUSED],
    ["error.provider-rejected-request.502.json", ERROR_KIND.PROVIDER_REFUSED],
    ["error.provider-unavailable.submission-unknown.502.json", ERROR_KIND.SERVER],
    ["error.cost-unverified.502.json", ERROR_KIND.SERVER],
  ];
  it.each(cases)("%s → %s", (file, kind) => {
    expect(classifyError(fixtureError(file)).kind).toBe(kind);
  });

  it("a bare 429 (no code) is rate-limited too; a bare 402 is a provider refusal", () => {
    expect(classifyError({ status: 429 })).toMatchObject({ kind: ERROR_KIND.RATE_LIMITED, code: "HTTP_429" });
    expect(classifyError({ status: 402 })).toMatchObject({ kind: ERROR_KIND.PROVIDER_REFUSED, code: "HTTP_402" });
  });

  it("list 429 (QE nit): 'try again in a moment', with a Try again button, never the bare generic text", async () => {
    const { root } = setup({ listJobs: () => Promise.reject(fixtureError("error.provider-rate-limited.429.json")) });
    await flush();
    const p = panel(root);
    expect(p.getAttribute("data-panel")).toBe(ERROR_KIND.RATE_LIMITED);
    expect(p.getAttribute("data-code")).toBe("PROVIDER_RATE_LIMITED");
    expect(p.textContent).toContain("Try again in a moment.");
    expect(byTag(p, "p")[0].textContent).toBe(LIST_MESSAGES[ERROR_KIND.RATE_LIMITED]);
    expect(byTag(p, "p")[0].textContent).not.toBe(LIST_MESSAGES[ERROR_KIND.REQUEST]); // not the bare generic line
    expect(button(root, "retry")).not.toBeNull();
  });

  it("asset 429 wording keeps the acceptance prefix and says 'try again in a moment'", () => {
    expect(ASSET_MESSAGES[ERROR_KIND.RATE_LIMITED]).toMatch(/^FurniAI couldn't get this file/);
    expect(ASSET_MESSAGES[ERROR_KIND.RATE_LIMITED]).toMatch(/Try again in a moment\.$/);
    expect(ASSET_MESSAGES[ERROR_KIND.RATE_LIMITED]).not.toMatch(/download|open|rate-limit/i);
  });

  it("Download: 429 twice → rate-limited message; one fresh re-resolve, no third call", async () => {
    const ok = byStatus("succeeded");
    const { root, client, downloads } = setupList([ok], {}, { getAssetUrl: () => { throw fixtureError("error.provider-rate-limited.429.json"); } });
    await flush();
    button(root, "download").click();
    await flush();
    expect(client.count("getAssetUrl")).toBe(2);
    expect(downloads).toHaveLength(0);
    const msg = byAttr(root, "data-asset-error", "PROVIDER_RATE_LIMITED")[0];
    expect(msg.textContent).toBe(ASSET_MESSAGES[ERROR_KIND.RATE_LIMITED]);
  });

  it("Download: 402 provider refusal is not retried and says so", async () => {
    const ok = byStatus("succeeded");
    const { root, client } = setupList([ok], {}, { getAssetUrl: () => { throw fixtureError("error.provider-insufficient-credits.402.json"); } });
    await flush();
    button(root, "download").click();
    await flush();
    expect(client.count("getAssetUrl")).toBe(1);
    expect(byAttr(root, "data-asset-error", "PROVIDER_INSUFFICIENT_CREDITS")[0].textContent).toBe(ASSET_MESSAGES[ERROR_KIND.PROVIDER_REFUSED]);
  });
});

describe("AE answers (Oct 5): Q14 source.isRetryable, 429 retry wait", () => {
  afterEach(() => vi.useRealTimers());
  const ok = () => byStatus("succeeded");

  it("Q14: a source with isRetryable(err) decides the Download retry (isRetryableResolveError is the fallback)", async () => {
    const job = ok();
    const seen = [];
    const source = {
      getJob: () => new Promise(() => {}),
      resolve: () => Promise.reject(Object.assign(new Error("x"), { status: 404, code: "MISSING_JOB" })),
      isRetryable: (e) => (seen.push(e.code), true), // a source that says even 404 is retryable
    };
    const downloads = [];
    const { root } = setup({ listJobs: () => ({ ok: true, jobs: [job] }) }, { noSource: true, creativeSource: source, startDownload: (d) => downloads.push(d) });
    await flush();
    button(root, "download").click();
    await flush();
    expect(seen).toEqual(["MISSING_JOB"]); // asked once, after the first failure; one retry at most
    expect(downloads).toHaveLength(0);
  });

  it("a 429 waits about a second before its one fresh re-resolve; nothing else waits", async () => {
    vi.useFakeTimers();
    const job = ok();
    let calls = 0;
    const downloads = [];
    const { root } = setupList([job], { rateLimitRetryDelayMs: undefined, startDownload: (d) => downloads.push(d) }, {
      getAssetUrl: () => {
        calls++;
        if (calls === 1) throw fixtureError("error.provider-rate-limited.429.json");
        return body("asset.200.json");
      },
    });
    await flush();
    button(root, "download").click();
    await flush();
    expect(calls).toBe(1);
    await vi.advanceTimersByTimeAsync(999);
    expect(calls).toBe(1);
    await vi.advanceTimersByTimeAsync(1);
    await flush();
    expect(calls).toBe(2);
    expect(downloads).toHaveLength(1);
  });
});
