import { describe, expect, it } from "vitest";
import { adaptWardrobeModelToFurniSpec } from "./wardrobeModelAdapter.js";
import { validateFurniSpec } from "../furnispec/validate.js";
import { buildStructuralPartGraph } from "./buildStructuralPartGraph.js";
import { buildPartGraphMeshes } from "../buildGeometry.js";
import { createWardrobe, addSection, addComponent } from "../wardrobe-model/kernel.js";
import { COMPONENT_TYPES } from "../wardrobe-model/schema.js";

describe("adaptWardrobeModelToFurniSpec", () => {
  it("adapts a basic WardrobeModel into a validated FurniSpec preserving specId and revision", () => {
    const wardrobeModel = {
      id: "wardrobe-customer-101",
      revision: 4,
      widthMm: 1800,
      heightMm: 2400,
      depthMm: 600,
      panelThicknessMm: 18,
      sections: [
        {
          id: "sec-01",
          widthMm: 873,
          components: [
            { id: "sh-01", type: "SHELF", positionMm: 400 },
            { id: "rail-01", type: "HANGING_RAIL", positionMm: 1400 },
          ],
        },
        {
          id: "sec-02",
          widthMm: 873,
          components: [
            { id: "db-01", type: "DRAWER_BANK", rows: 3, positionMm: 0 },
            { id: "sh-02", type: "SHELF", positionMm: 800 },
          ],
        },
      ],
    };

    const furniSpec = adaptWardrobeModelToFurniSpec(wardrobeModel);

    // Metadata preservation
    expect(furniSpec.specId).toBe("wardrobe-customer-101");
    expect(furniSpec.sourceSpecId).toBe("wardrobe-customer-101");
    expect(furniSpec.revision).toBe(4);

    // Envelopes and dimensions
    expect(furniSpec.envelope.widthMm).toBe(1800);
    expect(furniSpec.envelope.heightMm).toBe(2400);
    expect(furniSpec.envelope.depthMm).toBe(600);
    expect(furniSpec.carcass.heightMm).toBe(2300);
    expect(furniSpec.carcass.depthMm).toBe(580);
    expect(furniSpec.bays).toHaveLength(2);

    // Validation
    const val = validateFurniSpec(furniSpec);
    expect(val.errors).toEqual([]);
    expect(val.valid).toBe(true);

    // Consumed by buildStructuralPartGraph
    const partGraph = buildStructuralPartGraph(furniSpec);
    expect(partGraph).toBeDefined();
    expect(partGraph.parts.length).toBeGreaterThan(10);
    expect(partGraph.sourceSpecId).toBe("wardrobe-customer-101");

    // Consumed by buildPartGraphMeshes in buildGeometry.js
    const meshesGroup = buildPartGraphMeshes(partGraph, { showSystem32Pins: true });
    expect(meshesGroup.userData.panelCount).toBe(partGraph.parts.length);
    expect(meshesGroup.userData.system32Group.visible).toBe(true);
  });

  it("handles models generated by wardrobe-model kernel", () => {
    let model = createWardrobe({ widthMm: 2400, heightMm: 2600, depthMm: 600 });
    const sec1Id = model.sections[0].id;
    model = addSection(model, { widthMm: 1100, afterSectionId: sec1Id });
    model = addComponent(model, { sectionId: sec1Id, type: COMPONENT_TYPES.SHELF, positionMm: 500 });
    model = addComponent(model, { sectionId: sec1Id, type: COMPONENT_TYPES.HANGING_RAIL, positionMm: 1200 });

    const furniSpec = adaptWardrobeModelToFurniSpec(model);
    expect(furniSpec.revision).toBe(model.revision);
    expect(furniSpec.envelope.widthMm).toBe(2400);
    expect(furniSpec.envelope.heightMm).toBe(2600);

    const val = validateFurniSpec(furniSpec);
    expect(val.valid, `Validation failed: ${JSON.stringify(val.errors)}`).toBe(true);

    const partGraph = buildStructuralPartGraph(furniSpec);
    expect(partGraph.parts.length).toBeGreaterThan(0);
  });

  it("throws clear error on non-object or invalid dimensions", () => {
    expect(() => adaptWardrobeModelToFurniSpec(null)).toThrow(TypeError);
    expect(() => adaptWardrobeModelToFurniSpec({})).toThrow("wardrobeModel.widthMm must be a positive number.");
  });
});
