/**
 * The published fixture pack must be exactly what the handler answers today.
 * SIMULATED: the Scenario side is the local stand-in.
 */
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { buildFixtures, buildSyntheticGlb, FIXTURE_DIR, SYNTHETIC_GLB_NAME } from "../../../scripts/make-creative-fixtures.mjs";
import { CREATIVE_ERROR } from "./errors.js";
import { JOB_STATUS } from "./creativeService.js";

describe("fixture pack", () => {
  it("every committed JSON fixture equals a fresh capture, and none is missing or extra", async () => {
    const fresh = await buildFixtures();
    const onDisk = readdirSync(FIXTURE_DIR).filter((f) => f.endsWith(".json")).sort();
    expect(onDisk).toEqual(Object.keys(fresh).sort());
    for (const name of onDisk) expect(JSON.parse(readFileSync(path.join(FIXTURE_DIR, name), "utf8")), name).toEqual(fresh[name]);
  }, 20000);

  it("covers every job status and is labelled simulated throughout", async () => {
    const docs = readdirSync(FIXTURE_DIR).filter((f) => f.endsWith(".json")).map((f) => JSON.parse(readFileSync(path.join(FIXTURE_DIR, f), "utf8")));
    const text = JSON.stringify(docs);
    for (const s of Object.values(JOB_STATUS).filter((x) => x !== "submitting")) expect(text, s).toContain(`"status":"${s}"`);
    for (const d of docs) expect(d._fixture).toMatchObject({ simulated: true, generatedByScenario: false });
    for (const code of ["DUPLICATE_ACTIVE_JOB", "PRIOR_SUBMISSION_UNKNOWN", "INVALID_IMAGE", "COST_CAP_EXCEEDED", "PROVIDER_INSUFFICIENT_CREDITS", "ASSET_UNAVAILABLE"]) {
      expect(CREATIVE_ERROR[code]).toBe(code);
      expect(text).toContain(`"code":"${code}"`);
    }
    expect(text).not.toMatch(/sim-secret|sim-key|Basic /);
  });

  it("the GLB is a well-formed glTF 2.0 binary that declares itself synthetic", () => {
    const disk = readFileSync(path.join(FIXTURE_DIR, SYNTHETIC_GLB_NAME));
    expect(disk.equals(buildSyntheticGlb())).toBe(true);
    expect(disk.readUInt32LE(0)).toBe(0x46546c67);
    expect(disk.readUInt32LE(8)).toBe(disk.length);
    const jsonLen = disk.readUInt32LE(12);
    const gltf = JSON.parse(disk.toString("utf8", 20, 20 + jsonLen));
    expect(gltf.asset.generator).toMatch(/synthetic.*NOT generated by Scenario/i);
    expect(gltf.extras).toMatchObject({ synthetic: true, generatedByScenario: false });
    expect(disk.readUInt32LE(20 + jsonLen)).toBe(gltf.buffers[0].byteLength);
    expect(SYNTHETIC_GLB_NAME).toMatch(/^SYNTHETIC-.*not-scenario-generated/);
  });
});
